apiVersion: v1
name: istio-operator
version: 0.0.1-replace
appVersion: 1.8.1
description: Helm chart for the Istio Operator.
keywords:
  - kubernetes
  - istio
  - operator
  - service
  - mesh
home: https://istio.io/
icon: https://istio.io/latest/favicons/android-192x192.png
sources:
  - https://github.com/doflo-charts/helm-istio-operator
maintainers:
  - name: doFLo Infrastructure Team
    email: infra@doflo.com
    url: https://infra.doflo.com
